
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 27 2026 15:03:29 IST (Mar 27 2026 09:33:29 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [7:0] count;
  wire clk, m, rst;
  wire [7:0] count;
  wire n_0, n_1, n_4, n_7, n_10, n_12, n_26, n_31;
  wire n_43, n_52, n_64, n_66, n_68, n_69, n_71, n_72;
  wire n_75, n_77, n_83, n_86, n_89, n_90, n_98, n_101;
  wire n_103, n_107, n_109, n_114, n_120, n_122, n_123, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135;
  OAI21X1 g759__5107(.A0 (n_107), .A1 (n_128), .B0 (n_135), .Y (n_114));
  DFFRHQX4 \count_reg[2] (.RN (rst), .CK (clk), .D (n_126), .Q
       (count[2]));
  MXI2X1 g760__6783(.A (count[7]), .B (n_26), .S0 (n_98), .Y (n_109));
  MXI2X1 g781__5122(.A (count[3]), .B (n_1), .S0 (n_89), .Y (n_103));
  MXI2X1 g792__7098(.A (n_107), .B (m), .S0 (n_132), .Y (n_101));
  NAND2X2 g766__5115(.A (count[6]), .B (n_86), .Y (n_98));
  NOR2X1 g800__9315(.A (n_71), .B (n_75), .Y (n_89));
  NOR2X2 g778__1666(.A (n_4), .B (n_72), .Y (n_86));
  NOR2X2 g794__7410(.A (count[5]), .B (n_83), .Y (n_90));
  NOR2BX1 g801__2398(.AN (count[2]), .B (n_69), .Y (n_75));
  NOR4X2 g802__4319(.A (m), .B (count[0]), .C (count[2]), .D
       (count[1]), .Y (n_71));
  NAND2X2 g796__8428(.A (n_7), .B (n_68), .Y (n_83));
  NOR3X1 g808__6783(.A (m), .B (count[0]), .C (count[1]), .Y (n_66));
  NAND2X4 g790__3680(.A (count[4]), .B (n_64), .Y (n_72));
  NAND2X2 g797__1617(.A (n_52), .B (n_68), .Y (n_77));
  NAND3BX4 g807__2802(.AN (n_107), .B (count[0]), .C (count[1]), .Y
       (n_69));
  NOR2X4 g799__1705(.A (n_43), .B (n_31), .Y (n_64));
  NOR4X8 g804__5122(.A (count[0]), .B (count[3]), .C (count[1]), .D
       (count[2]), .Y (n_68));
  NOR3X2 g806__8246(.A (count[4]), .B (count[5]), .C (count[6]), .Y
       (n_52));
  NAND2X4 g811__7098(.A (count[0]), .B (count[1]), .Y (n_43));
  NAND2X4 g813__6131(.A (count[3]), .B (count[2]), .Y (n_31));
  INVXL g837(.A (m), .Y (n_107));
  MX2X1 g2(.A (n_133), .B (n_131), .S0 (m), .Y (n_120));
  NAND2X2 g888(.A (n_122), .B (n_107), .Y (n_123));
  MX2X4 g889(.A (n_26), .B (count[7]), .S0 (n_77), .Y (n_122));
  XNOR2X4 g891(.A (count[4]), .B (n_127), .Y (n_125));
  XNOR2X4 g892(.A (count[2]), .B (n_129), .Y (n_126));
  MXI2X1 g893(.A (n_64), .B (n_68), .S0 (n_107), .Y (n_127));
  DFFRX4 \count_reg[5] (.RN (rst), .CK (clk), .D (n_120), .Q
       (count[5]), .QN (n_4));
  DFFRX4 \count_reg[0] (.RN (rst), .CK (clk), .D (n_10), .Q (count[0]),
       .QN (n_10));
  DFFRX4 \count_reg[1] (.RN (rst), .CK (clk), .D (n_101), .Q
       (count[1]), .QN (n_0));
  DFFRX4 \count_reg[3] (.RN (rst), .CK (clk), .D (n_103), .Q
       (count[3]), .QN (n_1));
  DFFRX4 \count_reg[4] (.RN (rst), .CK (clk), .D (n_125), .Q
       (count[4]), .QN (n_7));
  DFFRX4 \count_reg[6] (.RN (rst), .CK (clk), .D (n_114), .Q
       (count[6]), .QN (n_12));
  DFFRX4 \count_reg[7] (.RN (rst), .CK (clk), .D (n_130), .Q
       (count[7]), .QN (n_26));
  XOR2X4 g908(.A (n_86), .B (n_12), .Y (n_128));
  NOR2BX4 g909(.AN (n_69), .B (n_66), .Y (n_129));
  OAI2BB1X4 g910(.A0N (m), .A1N (n_109), .B0 (n_123), .Y (n_130));
  XNOR2X4 g911(.A (count[5]), .B (n_72), .Y (n_131));
  OA22X4 g912(.A0 (count[1]), .A1 (n_10), .B0 (count[0]), .B1 (n_0), .Y
       (n_132));
  AO21X4 g913(.A0 (n_83), .A1 (count[5]), .B0 (n_90), .Y (n_133));
  NAND2X8 g914(.A (n_134), .B (n_107), .Y (n_135));
  OAI21X4 g3(.A0 (n_12), .A1 (n_90), .B0 (n_77), .Y (n_134));
endmodule

