/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID ECE-15.gsv.ac.in)
#  Generated on:      Wed Apr 15 12:14:47 2026
#  Design:            counter
#  Command:           saveNetlist counter_physical.v
###############################################################
*/
`timescale 1ns / 1ns
module counter (
	clk, 
	m, 
	rst, 
	count);
   input clk;
   input m;
   input rst;
   output [7:0] count;

   // Internal wires
   wire FE_DBTN0_count_2_65;
   wire \count[0]_63 ;
   wire \count[2]_65 ;
   wire \count[3]_66 ;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_76;
   wire n_87;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;

   INVX16 FE_DBTC0_count_2_65 (.Y(FE_DBTN0_count_2_65),
	.A(\count[2]_65 ));
   SDFFRHQX1 \count_reg[7]  (.Q(count[7]),
	.D(count[7]),
	.SE(n_48),
	.SI(n_0),
	.RN(rst),
	.CK(clk));
   SDFFRHQX8 \count_reg[6]  (.Q(count[6]),
	.D(count[6]),
	.SE(n_47),
	.SI(n_1),
	.RN(rst),
	.CK(clk));
   SDFFRHQX8 \count_reg[4]  (.Q(count[4]),
	.D(n_15),
	.SE(n_46),
	.SI(count[4]),
	.RN(rst),
	.CK(clk));
   SDFFRHQX8 \count_reg[5]  (.Q(count[5]),
	.D(count[5]),
	.SE(n_45),
	.SI(n_24),
	.RN(rst),
	.CK(clk));
   SDFFRHQX8 \count_reg[3]  (.Q(\count[3]_66 ),
	.D(count[3]),
	.SE(n_93),
	.SI(n_87),
	.RN(rst),
	.CK(clk));
   SDFFRHQX8 \count_reg[2]  (.Q(\count[2]_65 ),
	.D(\count[2]_65 ),
	.SE(n_44),
	.SI(FE_DBTN0_count_2_65),
	.RN(rst),
	.CK(clk));
   OAI22X4 g2994__2398 (.Y(n_48),
	.A0(n_94),
	.A1(n_39),
	.B0(n_31),
	.B1(n_38));
   OAI22X4 g2999__5107 (.Y(n_47),
	.A0(n_30),
	.A1(n_33),
	.B0(n_32),
	.B1(n_25));
   AOI22X4 g2996__6260 (.Y(n_46),
	.A0(n_14),
	.A1(n_41),
	.B0(n_40),
	.B1(n_90));
   OAI32X4 g3001__4319 (.Y(n_45),
	.A0(n_37),
	.A1(n_92),
	.A2(n_36),
	.B0(n_7),
	.B1(n_23));
   SDFFRHQX8 \count_reg[1]  (.Q(count[1]),
	.D(m),
	.SE(n_17),
	.SI(n_27),
	.RN(rst),
	.CK(clk));
   OAI31X4 g3002__8428 (.Y(n_44),
	.A0(count[1]),
	.A1(m),
	.A2(count[0]),
	.B0(n_28));
   NAND2X6 g3000__6783 (.Y(n_39),
	.A(n_41),
	.B(n_22));
   OR2X6 g3003__3680 (.Y(n_38),
	.A(n_37),
	.B(n_36));
   NAND2X4 g3009__2802 (.Y(n_33),
	.A(n_16),
	.B(n_19));
   NAND2X4 g3012__1705 (.Y(n_32),
	.A(n_3),
	.B(n_4));
   NAND2X4 g3013__5122 (.Y(n_31),
	.A(n_6),
	.B(n_11));
   NAND2X2 g3005__8246 (.Y(n_30),
	.A(n_76),
	.B(n_2));
   OR3X6 g3008__6131 (.Y(n_28),
	.A(n_27),
	.B(n_76),
	.C(n_18));
   OR3X1 g3007__1881 (.Y(n_25),
	.A(n_27),
	.B(n_76),
	.C(n_24));
   NAND2X4 g3011__5115 (.Y(n_23),
	.A(n_9),
	.B(n_13));
   CLKAND2X2 g3029__7482 (.Y(n_22),
	.A(FE_DBTN0_count_2_65),
	.B(n_87));
   CLKAND2X3 g3016__4733 (.Y(n_19),
	.A(FE_DBTN0_count_2_65),
	.B(n_18));
   XNOR2X1 g3014__6161 (.Y(n_17),
	.A(count[1]),
	.B(count[0]));
   CLKAND2X3 g3031__9315 (.Y(n_16),
	.A(n_15),
	.B(n_87));
   NOR3X4 g3006__9945 (.Y(n_14),
	.A(m),
	.B(\count[3]_66 ),
	.C(\count[2]_65 ));
   OR2X6 g3033__2883 (.Y(n_36),
	.A(n_76),
	.B(FE_DBTN0_count_2_65));
   DFFRHQX8 \count_reg[0]  (.Q(\count[0]_63 ),
	.D(n_76),
	.RN(rst),
	.CK(clk));
   NOR2X2 g3020__1666 (.Y(n_13),
	.A(\count[3]_66 ),
	.B(count[1]));
   AND2X2 g3021__7410 (.Y(n_12),
	.A(m),
	.B(\count[2]_65 ));
   CLKAND2X2 g3015__6417 (.Y(n_11),
	.A(count[5]),
	.B(\count[3]_66 ));
   NOR2X2 g3018__2398 (.Y(n_9),
	.A(m),
	.B(count[4]));
   NOR2X2 g3019__5107 (.Y(n_8),
	.A(m),
	.B(\count[2]_65 ));
   CLKAND2X2 g3032__6260 (.Y(n_40),
	.A(\count[0]_63 ),
	.B(count[1]));
   OR2X2 g3027__4319 (.Y(n_7),
	.A(\count[2]_65 ),
	.B(count[0]));
   CLKAND2X2 g3030__8428 (.Y(n_6),
	.A(m),
	.B(count[6]));
   CLKAND2X2 g3026__6783 (.Y(n_4),
	.A(\count[2]_65 ),
	.B(count[1]));
   CLKAND2X2 g3022__3680 (.Y(n_3),
	.A(\count[3]_66 ),
	.B(count[4]));
   NOR2X2 g3028__1617 (.Y(n_2),
	.A(m),
	.B(count[5]));
   NAND2X6 g3034__2802 (.Y(n_37),
	.A(count[1]),
	.B(count[4]));
   NOR2X4 g3023__1705 (.Y(n_41),
	.A(\count[0]_63 ),
	.B(count[1]));
   INVX4 g3036 (.Y(n_1),
	.A(count[6]));
   INVX2 g3044 (.Y(n_27),
	.A(m));
   INVX3 g3041 (.Y(n_0),
	.A(count[7]));
   INVX6 g3042 (.Y(n_18),
	.A(count[1]));
   INVX4 g3037 (.Y(n_24),
	.A(count[5]));
   INVX6 g3038 (.Y(n_15),
	.A(count[4]));
   INVXL fopt3059 (.Y(count[2]),
	.A(FE_DBTN0_count_2_65));
   INVX8 fopt3067 (.Y(count[0]),
	.A(n_76));
   INVX16 fopt3068 (.Y(n_76),
	.A(\count[0]_63 ));
   INVX6 fopt7 (.Y(count[3]),
	.A(n_87));
   CLKINVX12 fopt10 (.Y(n_87),
	.A(\count[3]_66 ));
   NOR2X8 g2 (.Y(n_90),
	.A(n_27),
	.B(n_89));
   NAND2X8 g3 (.Y(n_89),
	.A(\count[3]_66 ),
	.B(\count[2]_65 ));
   OR2X6 g3035__3069 (.Y(n_92),
	.A(n_27),
	.B(n_87));
   AO22X4 g3071 (.Y(n_93),
	.A0(n_8),
	.A1(n_41),
	.B0(n_40),
	.B1(n_12));
   OR4X6 g3072 (.Y(n_94),
	.A(m),
	.B(count[6]),
	.C(count[5]),
	.D(count[4]));
endmodule

