
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 30 2026 14:52:48 IST (Mar 30 2026 09:22:48 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [7:0] count;
  wire clk, m, rst;
  wire [7:0] count;
  wire n_0, n_1, n_5, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_15, n_16, n_17, n_18, n_19, n_23;
  wire n_25, n_26, n_27, n_30, n_31, n_33, n_34, n_35;
  wire n_36, n_38, n_40, n_42, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_55, n_56, n_57;
  wire n_62, n_63, n_64, n_65, n_73, n_86, n_89, n_93;
  wire n_105, n_111, n_112, n_113, n_114, n_116, n_122;
  DFFRHQX4 \count_reg[4] (.RN (rst), .CK (clk), .D (n_57), .Q
       (count[4]));
  SDFFRHQX8 \count_reg[5] (.RN (rst), .CK (clk), .D (count[5]), .SE
       (n_56), .SI (n_15), .Q (count[5]));
  SDFFRHQX8 \count_reg[7] (.RN (rst), .CK (clk), .D (count[7]), .SE
       (n_52), .SI (n_0), .Q (count[7]));
  SDFFRHQX8 \count_reg[6] (.RN (rst), .CK (clk), .D (count[6]), .SE
       (n_55), .SI (n_7), .Q (count[6]));
  SDFFRHQX8 \count_reg[3] (.RN (rst), .CK (clk), .D (n_49), .SE (n_89),
       .SI (n_50), .Q (count[3]));
  NAND2X4 g5149__2398(.A (n_114), .B (n_51), .Y (n_57));
  SDFFRHQX8 \count_reg[2] (.RN (rst), .CK (clk), .D (count[2]), .SE
       (n_48), .SI (n_10), .Q (count[2]));
  OAI21X4 g5151__5107(.A0 (n_73), .A1 (n_40), .B0 (n_34), .Y (n_56));
  OAI32X4 g5160__6260(.A0 (n_18), .A1 (n_73), .A2 (n_111), .B0 (n_26),
       .B1 (n_65), .Y (n_55));
  OAI21X4 g5162__8428(.A0 (n_31), .A1 (n_17), .B0 (n_46), .Y (n_52));
  AOI22X4 g5154__5526(.A0 (n_33), .A1 (n_122), .B0 (n_44), .B1 (n_62),
       .Y (n_51));
  SDFFRHQX8 \count_reg[1] (.RN (rst), .CK (clk), .D (n_38), .SE (m),
       .SI (n_64), .Q (count[1]));
  INVX2 g5156(.A (n_49), .Y (n_50));
  OAI21X4 g5158__6783(.A0 (m), .A1 (n_47), .B0 (n_93), .Y (n_48));
  OAI21X4 g5157__3680(.A0 (n_12), .A1 (n_47), .B0 (n_30), .Y (n_49));
  NAND2X6 g5166__1617(.A (n_36), .B (n_35), .Y (n_46));
  AOI21X2 g5155__2802(.A0 (n_44), .A1 (n_63), .B0 (n_42), .Y (n_45));
  NAND2X6 g5161__5122(.A (n_9), .B (n_63), .Y (n_40));
  INVX3 g5163(.A (n_64), .Y (n_38));
  NOR2X4 g5178__7098(.A (n_8), .B (n_16), .Y (n_36));
  NOR2X4 g5173__6131(.A (n_23), .B (n_13), .Y (n_35));
  NAND3X4 g5167__1881(.A (n_5), .B (n_19), .C (n_33), .Y (n_34));
  NAND2X4 g5169__7482(.A (n_25), .B (n_112), .Y (n_31));
  NAND2X4 g5168__4733(.A (n_112), .B (n_27), .Y (n_30));
  NAND2X4 g5174__9945(.A (n_1), .B (n_33), .Y (n_26));
  NAND3X4 g5176__2883(.A (m), .B (count[5]), .C (count[1]), .Y (n_18));
  NAND4X4 g5177__2346(.A (m), .B (count[6]), .C (count[5]), .D
       (count[1]), .Y (n_17));
  NAND2X4 g5183__1666(.A (n_42), .B (n_15), .Y (n_16));
  NAND2X4 g5182__6417(.A (n_86), .B (n_116), .Y (n_13));
  NOR2X6 g5184__5477(.A (n_11), .B (n_105), .Y (n_27));
  AND3X6 g5179__2398(.A (m), .B (count[3]), .C (count[2]), .Y (n_44));
  NAND2X2 g5195__5107(.A (n_11), .B (n_10), .Y (n_12));
  NOR2X4 g5194__6260(.A (n_11), .B (n_10), .Y (n_9));
  NAND2X4 g5193__4319(.A (n_11), .B (n_7), .Y (n_8));
  NAND2X8 g5197__8428(.A (n_10), .B (n_105), .Y (n_23));
  NOR2X8 g5187__5526(.A (n_42), .B (n_86), .Y (n_25));
  NAND2X4 g5198__3680(.A (n_105), .B (n_116), .Y (n_47));
  DFFRHQX8 \count_reg[0] (.RN (rst), .CK (clk), .D (n_116), .Q
       (count[0]));
  NOR2X2 g5192__1617(.A (m), .B (count[5]), .Y (n_1));
  NOR2X4 g5186__2802(.A (count[4]), .B (count[3]), .Y (n_33));
  NOR2X4 g5196__1705(.A (m), .B (count[1]), .Y (n_5));
  NOR2X4 g5185__5122(.A (count[0]), .B (count[2]), .Y (n_19));
  INVX4 g5200(.A (count[7]), .Y (n_0));
  INVX1 g5204(.A (m), .Y (n_11));
  INVX4 g5206(.A (count[5]), .Y (n_15));
  INVX6 g5205(.A (count[6]), .Y (n_7));
  INVX6 g5201(.A (count[4]), .Y (n_42));
  INVX16 g5208(.A (count[2]), .Y (n_10));
  AND3X4 g2(.A (count[0]), .B (count[1]), .C (n_42), .Y (n_62));
  ADDHX4 g5165__5217(.A (count[1]), .B (count[0]), .CO (n_63), .S
       (n_64));
  OR2X6 g5218(.A (count[0]), .B (n_23), .Y (n_65));
  INVX8 fopt5219(.A (n_25), .Y (n_73));
  INVX8 fopt5228(.A (n_86), .Y (n_89));
  INVX12 fopt5230(.A (count[3]), .Y (n_86));
  NAND2BX4 g5231(.AN (n_116), .B (n_27), .Y (n_93));
  INVX16 fopt5235(.A (count[1]), .Y (n_105));
  OR2X6 g5236(.A (n_10), .B (n_116), .Y (n_111));
  NOR2X6 g5199__5237(.A (n_10), .B (n_116), .Y (n_112));
  OAI21X4 g5238(.A0 (n_113), .A1 (n_47), .B0 (n_45), .Y (n_114));
  OR3X1 g3(.A (m), .B (count[3]), .C (count[2]), .Y (n_113));
  INVX12 fopt3(.A (count[0]), .Y (n_116));
  AND2X6 g5241(.A (n_5), .B (n_19), .Y (n_122));
endmodule

