
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr  7 2026 11:20:59 IST (Apr  7 2026 05:50:59 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [7:0] count;
  wire clk, m, rst;
  wire [7:0] count;
  wire \count[0]_63 , \count[2]_65 , \count[3]_66 , n_0, n_1, n_2, n_3,
       n_4;
  wire n_6, n_7, n_8, n_9, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_22, n_23, n_24;
  wire n_25, n_27, n_28, n_30, n_31, n_32, n_33, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_44, n_45, n_46;
  wire n_47, n_48, n_69, n_70, n_71, n_73, n_76, n_77;
  wire n_80, n_86, n_87, n_89, n_90, n_92, n_93, n_94;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (count[7]), .SI
       (n_0), .SE (n_48), .Q (count[7]));
  SDFFRHQX8 \count_reg[6] (.RN (rst), .CK (clk), .D (count[6]), .SI
       (n_1), .SE (n_47), .Q (count[6]));
  SDFFRHQX8 \count_reg[4] (.RN (rst), .CK (clk), .D (n_15), .SI
       (count[4]), .SE (n_46), .Q (count[4]));
  SDFFRHQX8 \count_reg[5] (.RN (rst), .CK (clk), .D (count[5]), .SI
       (n_24), .SE (n_45), .Q (count[5]));
  SDFFRHQX8 \count_reg[3] (.RN (rst), .CK (clk), .D (count[3]), .SI
       (n_86), .SE (n_93), .Q (\count[3]_66 ));
  SDFFRHQX8 \count_reg[2] (.RN (rst), .CK (clk), .D (n_70), .SI (n_69),
       .SE (n_44), .Q (\count[2]_65 ));
  OAI22X4 g2994__2398(.A0 (n_94), .A1 (n_39), .B0 (n_31), .B1 (n_38),
       .Y (n_48));
  OAI22X4 g2999__5107(.A0 (n_30), .A1 (n_33), .B0 (n_32), .B1 (n_25),
       .Y (n_47));
  AOI22X4 g2996__6260(.A0 (n_14), .A1 (n_41), .B0 (n_40), .B1 (n_90),
       .Y (n_46));
  OAI32X4 g3001__4319(.A0 (n_37), .A1 (n_92), .A2 (n_36), .B0 (n_7),
       .B1 (n_23), .Y (n_45));
  SDFFRHQX8 \count_reg[1] (.RN (rst), .CK (clk), .D (m), .SI (n_27),
       .SE (n_17), .Q (count[1]));
  OAI31X4 g3002__8428(.A0 (count[1]), .A1 (m), .A2 (count[0]), .B0
       (n_28), .Y (n_44));
  NAND2X6 g3000__6783(.A (n_41), .B (n_22), .Y (n_39));
  OR2X6 g3003__3680(.A (n_37), .B (n_36), .Y (n_38));
  NAND2X4 g3009__2802(.A (n_16), .B (n_19), .Y (n_33));
  NAND2X4 g3012__1705(.A (n_3), .B (n_4), .Y (n_32));
  NAND2X4 g3013__5122(.A (n_6), .B (n_11), .Y (n_31));
  NAND2X2 g3005__8246(.A (n_76), .B (n_2), .Y (n_30));
  OR3X6 g3008__6131(.A (n_27), .B (n_76), .C (n_18), .Y (n_28));
  OR3X1 g3007__1881(.A (n_27), .B (n_76), .C (n_24), .Y (n_25));
  NAND2X4 g3011__5115(.A (n_9), .B (n_13), .Y (n_23));
  CLKAND2X2 g3029__7482(.A (n_73), .B (n_87), .Y (n_22));
  CLKAND2X3 g3016__4733(.A (n_73), .B (n_18), .Y (n_19));
  XNOR2X1 g3014__6161(.A (count[1]), .B (n_80), .Y (n_17));
  CLKAND2X3 g3031__9315(.A (n_15), .B (n_87), .Y (n_16));
  NOR3X4 g3006__9945(.A (m), .B (\count[3]_66 ), .C (\count[2]_65 ), .Y
       (n_14));
  OR2X6 g3033__2883(.A (n_76), .B (n_73), .Y (n_36));
  DFFRHQX8 \count_reg[0] (.RN (rst), .CK (clk), .D (n_77), .Q
       (\count[0]_63 ));
  NOR2X2 g3020__1666(.A (\count[3]_66 ), .B (count[1]), .Y (n_13));
  AND2X2 g3021__7410(.A (m), .B (\count[2]_65 ), .Y (n_12));
  CLKAND2X2 g3015__6417(.A (count[5]), .B (\count[3]_66 ), .Y (n_11));
  NOR2X2 g3018__2398(.A (m), .B (count[4]), .Y (n_9));
  NOR2X2 g3019__5107(.A (m), .B (\count[2]_65 ), .Y (n_8));
  CLKAND2X2 g3032__6260(.A (\count[0]_63 ), .B (count[1]), .Y (n_40));
  OR2X2 g3027__4319(.A (\count[2]_65 ), .B (n_80), .Y (n_7));
  CLKAND2X2 g3030__8428(.A (m), .B (count[6]), .Y (n_6));
  CLKAND2X2 g3026__6783(.A (\count[2]_65 ), .B (count[1]), .Y (n_4));
  CLKAND2X2 g3022__3680(.A (\count[3]_66 ), .B (count[4]), .Y (n_3));
  NOR2X2 g3028__1617(.A (m), .B (count[5]), .Y (n_2));
  NAND2X6 g3034__2802(.A (count[1]), .B (count[4]), .Y (n_37));
  NOR2X4 g3023__1705(.A (\count[0]_63 ), .B (count[1]), .Y (n_41));
  INVX4 g3036(.A (count[6]), .Y (n_1));
  INVX2 g3044(.A (m), .Y (n_27));
  INVX3 g3041(.A (count[7]), .Y (n_0));
  INVX6 g3042(.A (count[1]), .Y (n_18));
  INVX4 g3037(.A (count[5]), .Y (n_24));
  INVX6 g3038(.A (count[4]), .Y (n_15));
  INVXL fopt3059(.A (n_69), .Y (count[2]));
  INVX6 fopt3060(.A (n_70), .Y (n_69));
  CLKBUFX6 fopt3061(.A (n_71), .Y (n_70));
  BUFX6 fopt3062(.A (\count[2]_65 ), .Y (n_71));
  INVX16 fopt3063(.A (\count[2]_65 ), .Y (n_73));
  INVX6 fopt3064(.A (count[0]), .Y (n_77));
  BUFX6 fopt3066(.A (n_80), .Y (count[0]));
  INVX8 fopt3067(.A (n_76), .Y (n_80));
  INVX16 fopt3068(.A (\count[0]_63 ), .Y (n_76));
  INVX6 fopt7(.A (n_86), .Y (count[3]));
  BUFX6 fopt9(.A (n_87), .Y (n_86));
  CLKINVX12 fopt10(.A (\count[3]_66 ), .Y (n_87));
  NOR2X8 g2(.A (n_27), .B (n_89), .Y (n_90));
  NAND2X8 g3(.A (\count[3]_66 ), .B (n_71), .Y (n_89));
  OR2X6 g3035__3069(.A (n_27), .B (n_87), .Y (n_92));
  AO22X4 g3071(.A0 (n_8), .A1 (n_41), .B0 (n_40), .B1 (n_12), .Y
       (n_93));
  OR4X6 g3072(.A (m), .B (count[6]), .C (count[5]), .D (count[4]), .Y
       (n_94));
endmodule

