
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 30 2026 15:27:23 IST (Mar 30 2026 09:57:23 UTC)

// Verification Directory fv/seq_det_1010_mealy 

module seq_det_1010_mealy(clk, reset, din, dout);
  input clk, reset, din;
  output dout;
  wire clk, reset, din;
  wire dout;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  DFFRHQX4 \state_reg[1] (.RN (n_7), .CK (clk), .D (n_8), .Q
       (state[1]));
  NAND2X4 g230__2398(.A (n_1), .B (n_6), .Y (n_8));
  DFFRHQX4 \state_reg[0] (.RN (n_7), .CK (clk), .D (n_3), .Q
       (state[0]));
  NAND3X8 g233__5107(.A (n_2), .B (state[0]), .C (n_4), .Y (n_6));
  NOR3X2 g232__6260(.A (din), .B (n_0), .C (n_4), .Y (dout));
  AOI21X2 g231__4319(.A0 (state[0]), .A1 (state[1]), .B0 (n_2), .Y
       (n_3));
  NAND2X2 g234__8428(.A (din), .B (state[1]), .Y (n_1));
  INVX4 g237(.A (state[0]), .Y (n_0));
  INVX6 g235(.A (state[1]), .Y (n_4));
  INVX1 g238(.A (din), .Y (n_2));
  INVX1 g236(.A (reset), .Y (n_7));
endmodule

