
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 30 2026 15:41:28 IST (Mar 30 2026 10:11:28 UTC)

// Verification Directory fv/seq_det_1010_moore 

module seq_det_1010_moore(clk, reset, din, dout);
  input clk, reset, din;
  output dout;
  wire clk, reset, din;
  wire dout;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_18, n_19, n_23;
  wire n_24, n_25, n_26, n_27, n_28;
  DFFRHQX8 \state_reg[1] (.RN (n_19), .CK (clk), .D (n_18), .Q
       (state[1]));
  DFFRHQX2 dout_reg(.RN (n_19), .CK (clk), .D (n_24), .Q (dout));
  OAI221X4 g837__2398(.A0 (n_27), .A1 (n_10), .B0 (n_9), .B1 (n_26),
       .C0 (n_12), .Y (n_18));
  DFFRHQX4 \state_reg[2] (.RN (n_19), .CK (clk), .D (n_14), .Q
       (state[2]));
  DFFRHQX8 \state_reg[0] (.RN (n_19), .CK (clk), .D (n_15), .Q
       (state[0]));
  OAI21X2 g840__6260(.A0 (n_25), .A1 (n_11), .B0 (n_1), .Y (n_15));
  OAI22X2 g839__4319(.A0 (n_4), .A1 (n_0), .B0 (n_26), .B1 (n_5), .Y
       (n_14));
  NAND2X4 g842__8428(.A (n_28), .B (n_3), .Y (n_13));
  INVX3 g843(.A (n_11), .Y (n_12));
  INVX6 g844(.A (n_9), .Y (n_10));
  NOR2X6 g846__6783(.A (n_4), .B (n_5), .Y (n_11));
  NAND2X8 g847__3680(.A (n_4), .B (n_5), .Y (n_9));
  NOR2X6 g850__1617(.A (state[1]), .B (n_4), .Y (n_3));
  NAND2X2 g852__2802(.A (n_4), .B (state[1]), .Y (n_2));
  NAND2X2 g845__5122(.A (state[2]), .B (state[0]), .Y (n_1));
  NOR2X1 g851__8246(.A (state[1]), .B (state[0]), .Y (n_0));
  INVX12 g855(.A (state[1]), .Y (n_5));
  INVX1 g854(.A (reset), .Y (n_19));
  INVX12 g857(.A (state[2]), .Y (n_4));
  OAI21X4 g2(.A0 (n_23), .A1 (n_2), .B0 (n_13), .Y (n_24));
  NAND2BX2 g3(.AN (din), .B (state[0]), .Y (n_23));
  NAND2X6 g848__862(.A (n_25), .B (state[0]), .Y (n_26));
  INVX1 g863(.A (din), .Y (n_25));
  OR2X6 g864(.A (n_25), .B (state[0]), .Y (n_27));
  NOR2X4 g853__865(.A (n_25), .B (state[0]), .Y (n_28));
endmodule

