
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 30 2026 16:43:06 IST (Mar 30 2026 11:13:06 UTC)

// Verification Directory fv/seq_detector 

module seq_detector(clk, reset, i, out);
  input clk, reset, i;
  output out;
  wire clk, reset, i;
  wire out;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_14, n_16, n_21, n_25;
  wire n_27, n_28, n_29, n_30, n_31, n_32;
  DFFRHQX4 \state_reg[0] (.RN (n_21), .CK (clk), .D (n_30), .Q
       (state[0]));
  DFFRHQX4 \state_reg[1] (.RN (n_21), .CK (clk), .D (n_31), .Q
       (state[1]));
  DFFRHQX4 \state_reg[2] (.RN (n_21), .CK (clk), .D (n_12), .Q
       (state[2]));
  OAI22XL g780__6260(.A0 (n_4), .A1 (n_32), .B0 (n_11), .B1 (n_5), .Y
       (out));
  OAI21X4 g781__4319(.A0 (n_7), .A1 (n_1), .B0 (n_8), .Y (n_16));
  OAI22X4 g784__8428(.A0 (state[1]), .A1 (n_6), .B0 (n_25), .B1 (n_2),
       .Y (n_13));
  NOR2X4 g782__5526(.A (n_10), .B (n_11), .Y (n_12));
  NOR2X6 g785__6783(.A (n_0), .B (n_10), .Y (n_14));
  NOR2X4 g791__1617(.A (n_28), .B (n_6), .Y (n_7));
  NAND2X1 g792__2802(.A (n_4), .B (n_27), .Y (n_5));
  NAND2X8 g789__1705(.A (n_28), .B (n_2), .Y (n_10));
  NOR2X4 g790__5122(.A (n_25), .B (n_2), .Y (n_1));
  INVXL g796(.A (n_2), .Y (n_4));
  INVX16 g797(.A (n_2), .Y (n_6));
  NAND2BX4 g787__8246(.AN (i), .B (state[1]), .Y (n_0));
  NAND2X2 g793__7098(.A (i), .B (state[1]), .Y (n_11));
  NOR2X4 g788__6131(.A (i), .B (state[1]), .Y (n_8));
  INVX12 g798(.A (state[0]), .Y (n_2));
  INVX1 g794(.A (reset), .Y (n_21));
  INVX8 fopt(.A (n_28), .Y (n_25));
  INVX8 fopt3(.A (state[2]), .Y (n_28));
  NAND2BX4 g2(.AN (n_14), .B (n_29), .Y (n_30));
  NAND2X6 g3(.A (i), .B (n_13), .Y (n_29));
  NAND2BX4 g802(.AN (n_14), .B (n_16), .Y (n_31));
  NAND2BX1 g803(.AN (n_27), .B (n_8), .Y (n_32));
  BUFX2 fopt805(.A (n_28), .Y (n_27));
endmodule

