
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 28 2026 10:37:04 IST (Mar 28 2026 05:07:04 UTC)

// Verification Directory fv/mux_ff_ex 

module mux_ff_ex(i0, i1, i2, i3, clk, resetn, sel, q);
  input i0, i1, i2, i3, clk, resetn;
  input [1:0] sel;
  output q;
  wire i0, i1, i2, i3, clk, resetn;
  wire [1:0] sel;
  wire q;
  wire n_16;
  DFFRHQX4 q_out_reg(.RN (resetn), .CK (clk), .D (n_16), .Q (q));
  MX4X4 g2(.A (i0), .B (i2), .C (i1), .D (i3), .S0 (sel[1]), .S1
       (sel[0]), .Y (n_16));
endmodule

