
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr  2 2026 13:06:32 IST (Apr  2 2026 07:36:32 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count, SE, scan_in, scan_out);
  input clk, m, rst, SE, scan_in;
  output [7:0] count;
  output scan_out;
  wire clk, m, rst, SE, scan_in;
  wire [7:0] count;
  wire scan_out;
  wire n_5, n_6, n_7, n_9, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_27, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_37, n_38, n_39, n_41, n_42, n_47, n_48, n_49;
  wire n_50, n_51, n_52;
  assign scan_out = count[7];
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_47), .SI
       (count[4]), .SE (SE), .Q (count[5]));
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_42), .SI
       (count[6]), .SE (SE), .Q (count[7]));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_48), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_41), .SI
       (count[5]), .SE (SE), .Q (count[6]));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_39), .SI
       (count[3]), .SE (SE), .Q (count[4]));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_35), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  OAI21X1 g1105__5107(.A0 (n_37), .A1 (count[7]), .B0 (n_38), .Y
       (n_42));
  XOR2XL g1109__6260(.A (count[6]), .B (n_31), .Y (n_41));
  XNOR2X1 g1103__8428(.A (count[4]), .B (n_32), .Y (n_39));
  NAND2X1 g1107__5526(.A (n_37), .B (count[7]), .Y (n_38));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_27), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  MXI2XL g1106__3680(.A (n_33), .B (count[2]), .S0 (n_30), .Y (n_35));
  AOI21X1 g1115__1617(.A0 (n_17), .A1 (n_52), .B0 (n_24), .Y (n_37));
  OAI22XL g1111__2802(.A0 (n_51), .A1 (count[2]), .B0 (n_50), .B1
       (n_33), .Y (n_34));
  NOR2XL g1112__1705(.A (n_25), .B (n_20), .Y (n_32));
  OAI21X1 g1123__5122(.A0 (n_23), .A1 (n_22), .B0 (n_19), .Y (n_31));
  NAND2XL g1113__8246(.A (n_50), .B (n_51), .Y (n_30));
  XNOR2X1 g1114__7098(.A (m), .B (n_14), .Y (n_27));
  NOR3BX1 g1121__6131(.AN (count[6]), .B (n_23), .C (n_22), .Y (n_24));
  NAND2X1 g1125__1881(.A (n_16), .B (n_52), .Y (n_19));
  NOR2BX1 g1122__5115(.AN (n_12), .B (n_15), .Y (n_25));
  NOR2BX1 g1126__7482(.AN (n_16), .B (count[6]), .Y (n_17));
  NOR2X1 g1119__6161(.A (n_11), .B (n_9), .Y (n_20));
  SDFFRHQX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_13), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  NAND2X1 g1128__9315(.A (n_7), .B (n_33), .Y (n_15));
  MX2XL g1133__2883(.A (count[0]), .B (n_13), .S0 (count[1]), .Y
       (n_14));
  OR2XL g1131__2346(.A (n_6), .B (n_5), .Y (n_22));
  NAND3X1 g1127__7410(.A (m), .B (count[3]), .C (count[2]), .Y (n_11));
  NOR3X1 g1129__6417(.A (m), .B (count[5]), .C (count[4]), .Y (n_16));
  NAND3X1 g1132__5477(.A (m), .B (count[5]), .C (count[4]), .Y (n_23));
  NOR2X1 g1135__5107(.A (m), .B (count[3]), .Y (n_7));
  NAND2XL g1136__6260(.A (count[3]), .B (count[1]), .Y (n_6));
  NAND2XL g1138__4319(.A (count[0]), .B (count[2]), .Y (n_5));
  NOR2X1 g1141__5526(.A (count[1]), .B (count[0]), .Y (n_12));
  NAND2X1 g1140__6783(.A (count[1]), .B (count[0]), .Y (n_9));
  INVX1 g1144(.A (count[0]), .Y (n_13));
  INVX1 g1147(.A (count[2]), .Y (n_33));
  XOR2XL g2(.A (count[5]), .B (n_49), .Y (n_47));
  XOR2XL g1156(.A (count[3]), .B (n_34), .Y (n_48));
  MX2XL g1157(.A (n_25), .B (n_20), .S0 (count[4]), .Y (n_49));
  NAND2BX1 g1158(.AN (n_9), .B (m), .Y (n_50));
  NAND2BX1 g1159(.AN (m), .B (n_12), .Y (n_51));
  NOR4X1 g1160(.A (count[3]), .B (count[1]), .C (count[0]), .D
       (count[2]), .Y (n_52));
endmodule

