
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 15 2026 15:35:19 IST (Apr 15 2026 10:05:19 UTC)

// Verification Directory fv/async_fifo 

module async_fifo(wreq, wclk, wrst_n, rreq, rclk, rrst_n, wdata, rdata,
     wfull, rempty);
  input wreq, wclk, wrst_n, rreq, rclk, rrst_n;
  input [7:0] wdata;
  output [7:0] rdata;
  output wfull, rempty;
  wire wreq, wclk, wrst_n, rreq, rclk, rrst_n;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [3:0] wptr;
  wire [3:0] wq2_rptr;
  wire [3:0] rq2_wptr;
  wire [3:0] wq1_rptr;
  wire [3:0] rq1_wptr;
  wire [3:0] rptr;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[15] ;
  wire [4:0] rbin;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[5] ;
  wire [4:0] wbin;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[7] ;
  wire UNCONNECTED, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_13, n_14, n_16, n_17, n_19, n_20;
  wire n_21, n_22, n_24, n_25, n_26, n_27, n_28, n_31;
  wire n_32, n_38, n_39, n_40, n_41, n_44, n_45, n_48;
  wire n_51, n_54, n_56, n_57, n_58, n_59, n_62, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_71, n_72, n_76;
  wire n_79, n_81, n_82, n_83, n_84, n_86, n_91, n_92;
  wire n_97, n_98, n_100, n_102, n_104, n_105, n_106, n_107;
  wire n_109, n_110, n_111, n_112, n_115, n_121, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_134, n_135;
  wire n_136, n_138, n_142, n_143, n_145, n_146, n_148, n_149;
  wire n_150, n_153, n_154, n_155, n_157, n_158, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_195;
  wire n_196, n_198, n_211, n_212, n_213, n_214, n_224, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_245, n_246, n_247, n_248, n_251, n_259, n_262, n_263;
  wire n_264, n_270, n_273, n_275, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_324;
  wire n_325, n_326, n_327, n_328, n_331, n_332, n_333, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_347, n_348, n_349;
  wire n_350, n_351, n_352, n_353, n_354, n_355, n_356, n_357;
  wire n_358, n_359, n_366, n_367, n_368, n_369, n_370, n_371;
  wire n_372, n_373, n_374, n_375, n_376, n_377, n_378, n_379;
  wire n_380, n_381, n_382, n_383, n_384, n_385, n_386, n_387;
  wire n_388, n_389, n_390, n_391, n_392, n_393, n_394, n_395;
  wire n_396, n_397, n_398, n_399, n_400, n_401, n_402, n_403;
  wire n_405, n_406, n_409, n_410, n_411, n_412, n_413, n_414;
  wire n_415, n_416, n_418, n_426, n_427, n_428, n_432, n_433;
  wire n_438, n_440, n_441;
  DFFRHQX1 wfull_reg(.RN (wrst_n), .CK (wclk), .D (n_359), .Q (wfull));
  NOR2X1 g12412__2398(.A (n_355), .B (n_357), .Y (n_359));
  NOR2XL g12411__5107(.A (n_354), .B (n_356), .Y (n_358));
  NAND3X1 g12414__6260(.A (wptr[3]), .B (n_344), .C (n_352), .Y
       (n_357));
  NAND2XL g12413__4319(.A (n_349), .B (n_353), .Y (n_356));
  AOI31X1 g12415__8428(.A0 (wq2_rptr[2]), .A1 (wptr[2]), .A2
       (wq2_rptr[3]), .B0 (n_351), .Y (n_355));
  NAND2X1 g12416__5526(.A (n_348), .B (n_350), .Y (n_354));
  MXI2XL g12420__6783(.A (n_343), .B (rq2_wptr[3]), .S0 (n_324), .Y
       (n_353));
  XNOR2X1 g12422__3680(.A (wq2_rptr[1]), .B (wptr[1]), .Y (n_352));
  NOR3X1 g12417__1617(.A (wq2_rptr[2]), .B (wptr[2]), .C (wq2_rptr[3]),
       .Y (n_351));
  NOR2X1 g12419__2802(.A (n_345), .B (n_347), .Y (n_350));
  MXI2XL g12421__1705(.A (n_342), .B (rq2_wptr[2]), .S0 (n_332), .Y
       (n_349));
  AOI21X1 g12418__5122(.A0 (rq2_wptr[1]), .A1 (n_368), .B0 (n_341), .Y
       (n_348));
  NOR2X1 g12423__8246(.A (rq2_wptr[1]), .B (n_368), .Y (n_347));
  OAI2BB1X1 g12424__7098(.A0N (rq2_wptr[0]), .A1N (n_340), .B0 (n_297),
       .Y (n_345));
  XNOR2X1 g12425__6131(.A (wq2_rptr[0]), .B (wptr[0]), .Y (n_344));
  DFFRHQX1 \wq2_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[1]), .Q (wq2_rptr[1]));
  DFFRHQX1 \wq2_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[2]), .Q (wq2_rptr[2]));
  NOR2XL g12431__1881(.A (rq2_wptr[0]), .B (n_340), .Y (n_341));
  DFFRX1 \wq2_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (wq1_rptr[3]),
       .Q (UNCONNECTED), .QN (wq2_rptr[3]));
  DFFRHQX1 \rq2_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D
       (rq1_wptr[1]), .Q (rq2_wptr[1]));
  DFFRHQX1 \wq1_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (rptr[2]), .Q
       (wq1_rptr[2]));
  DFFRHQX1 \wq1_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (rptr[1]), .Q
       (wq1_rptr[1]));
  DFFRHQX1 \rq1_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (wptr[3]), .Q
       (rq1_wptr[3]));
  DFFRHQX1 \wq2_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[0]), .Q (wq2_rptr[0]));
  DFFRHQX1 \wq1_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (rptr[3]), .Q
       (wq1_rptr[3]));
  DFFRHQX1 \rq2_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D
       (rq1_wptr[0]), .Q (rq2_wptr[0]));
  DFFRHQX1 \rq1_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (wptr[2]), .Q
       (rq1_wptr[2]));
  DFFRHQX1 \rq1_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (wptr[1]), .Q
       (rq1_wptr[1]));
  DFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_333), .Q
       (rptr[2]));
  DFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_331), .Q
       (rptr[1]));
  NAND3XL g12449__5115(.A (n_288), .B (n_309), .C (n_304), .Y
       (rdata[4]));
  NAND3XL g12524__7482(.A (n_248), .B (n_293), .C (n_308), .Y
       (rdata[5]));
  NAND3XL g12522__4733(.A (n_251), .B (n_282), .C (n_301), .Y
       (rdata[6]));
  NAND3XL g12519__6161(.A (n_232), .B (n_287), .C (n_302), .Y
       (rdata[3]));
  NAND3XL g12518__9315(.A (n_231), .B (n_284), .C (n_303), .Y
       (rdata[2]));
  DFFRHQX1 \rq1_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (wptr[0]), .Q
       (rq1_wptr[0]));
  NAND3XL g12523__9945(.A (n_247), .B (n_283), .C (n_300), .Y
       (rdata[1]));
  DFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_325), .Q
       (rptr[3]));
  DFFRHQX1 \wq1_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (rptr[0]), .Q
       (wq1_rptr[0]));
  DFFRHQX1 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_367), .Q
       (wptr[3]));
  INVX1 g12516(.A (n_332), .Y (n_333));
  INVXL g12517(.A (n_368), .Y (n_331));
  NAND2XL g12526__2883(.A (n_310), .B (n_306), .Y (rdata[0]));
  NAND2XL g12525__2346(.A (n_307), .B (n_305), .Y (rdata[7]));
  SDFFQX1 \mem_reg[10][6] (.CK (wclk), .D (\mem[10] [6]), .SI
       (wdata[6]), .SE (n_328), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[10][3] (.CK (wclk), .D (\mem[10] [3]), .SI
       (wdata[3]), .SE (n_328), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][5] (.CK (wclk), .D (\mem[10] [5]), .SI
       (wdata[5]), .SE (n_328), .Q (\mem[10] [5]));
  DFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_314), .Q
       (wptr[1]));
  SDFFQX1 \mem_reg[10][7] (.CK (wclk), .D (\mem[10] [7]), .SI
       (wdata[7]), .SE (n_328), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[10][1] (.CK (wclk), .D (\mem[10] [1]), .SI
       (wdata[1]), .SE (n_328), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[10][0] (.CK (wclk), .D (\mem[10] [0]), .SI
       (wdata[0]), .SE (n_328), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[12][0] (.CK (wclk), .D (\mem[12] [0]), .SI
       (wdata[0]), .SE (n_327), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (wclk), .D (\mem[12] [1]), .SI
       (wdata[1]), .SE (n_327), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[10][4] (.CK (wclk), .D (\mem[10] [4]), .SI
       (wdata[4]), .SE (n_328), .Q (\mem[10] [4]));
  DFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_313), .Q
       (wptr[2]));
  SDFFQX1 \mem_reg[10][2] (.CK (wclk), .D (\mem[10] [2]), .SI
       (wdata[2]), .SE (n_328), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (wclk), .D (\mem[12] [3]), .SI
       (wdata[3]), .SE (n_327), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (wclk), .D (\mem[12] [4]), .SI
       (wdata[4]), .SE (n_327), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][5] (.CK (wclk), .D (\mem[12] [5]), .SI
       (wdata[5]), .SE (n_327), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][6] (.CK (wclk), .D (\mem[12] [6]), .SI
       (wdata[6]), .SE (n_327), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[12][7] (.CK (wclk), .D (\mem[12] [7]), .SI
       (wdata[7]), .SE (n_327), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[14][0] (.CK (wclk), .D (\mem[14] [0]), .SI
       (wdata[0]), .SE (n_326), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[12][2] (.CK (wclk), .D (\mem[12] [2]), .SI
       (wdata[2]), .SE (n_327), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[14][1] (.CK (wclk), .D (\mem[14] [1]), .SI
       (wdata[1]), .SE (n_326), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][2] (.CK (wclk), .D (\mem[14] [2]), .SI
       (wdata[2]), .SE (n_326), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[14][3] (.CK (wclk), .D (\mem[14] [3]), .SI
       (wdata[3]), .SE (n_326), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][4] (.CK (wclk), .D (\mem[14] [4]), .SI
       (wdata[4]), .SE (n_326), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[14][5] (.CK (wclk), .D (\mem[14] [5]), .SI
       (wdata[5]), .SE (n_326), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[14][6] (.CK (wclk), .D (\mem[14] [6]), .SI
       (wdata[6]), .SE (n_326), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[14][7] (.CK (wclk), .D (\mem[14] [7]), .SI
       (wdata[7]), .SE (n_326), .Q (\mem[14] [7]));
  INVX1 g12515(.A (n_324), .Y (n_325));
  DFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_295), .Q
       (rptr[0]));
  SDFFQX1 \mem_reg[11][0] (.CK (wclk), .D (\mem[11] [0]), .SI
       (wdata[0]), .SE (n_322), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][2] (.CK (wclk), .D (\mem[11] [2]), .SI
       (wdata[2]), .SE (n_322), .Q (\mem[11] [2]));
  SDFFQX1 \mem_reg[11][3] (.CK (wclk), .D (\mem[11] [3]), .SI
       (wdata[3]), .SE (n_322), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[6][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[6] [6]),
       .SE (n_317), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[11][1] (.CK (wclk), .D (\mem[11] [1]), .SI
       (wdata[1]), .SE (n_322), .Q (\mem[11] [1]));
  DFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_369), .Q
       (wptr[0]));
  SDFFQX1 \mem_reg[4][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[4] [4]),
       .SE (n_321), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[0] [5]),
       .SE (n_320), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[4] [6]),
       .SE (n_321), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[0] [7]),
       .SE (n_320), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[0] [3]),
       .SE (n_320), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[0] [6]),
       .SE (n_320), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (wclk), .D (\mem[13] [7]), .SI
       (wdata[7]), .SE (n_319), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[13][3] (.CK (wclk), .D (\mem[13] [3]), .SI
       (wdata[3]), .SE (n_319), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[13][0] (.CK (wclk), .D (\mem[13] [0]), .SI
       (wdata[0]), .SE (n_319), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[11][7] (.CK (wclk), .D (\mem[11] [7]), .SI
       (wdata[7]), .SE (n_322), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[8][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[8] [5]),
       .SE (n_316), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[9][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[9] [5]),
       .SE (n_315), .Q (\mem[9] [5]));
  NOR2BX1 g12580__7410(.AN (n_289), .B (n_292), .Y (n_332));
  SDFFQX1 \mem_reg[2][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[2] [0]),
       .SE (n_318), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[2] [1]),
       .SE (n_318), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[2] [2]),
       .SE (n_318), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[2] [3]),
       .SE (n_318), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[2] [4]),
       .SE (n_318), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[2] [5]),
       .SE (n_318), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[0] [1]),
       .SE (n_320), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[2][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[2] [7]),
       .SE (n_318), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[4][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[4] [0]),
       .SE (n_321), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[4] [1]),
       .SE (n_321), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[4] [2]),
       .SE (n_321), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[4] [3]),
       .SE (n_321), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[0] [0]),
       .SE (n_320), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[4][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[4] [7]),
       .SE (n_321), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[6][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[6] [0]),
       .SE (n_317), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[6] [1]),
       .SE (n_317), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[6] [2]),
       .SE (n_317), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[6][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[6] [3]),
       .SE (n_317), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[6] [4]),
       .SE (n_317), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[6] [5]),
       .SE (n_317), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[6][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[6] [7]),
       .SE (n_317), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[8][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[8] [0]),
       .SE (n_316), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[8] [1]),
       .SE (n_316), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[8] [2]),
       .SE (n_316), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[8][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[8] [3]),
       .SE (n_316), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[8] [4]),
       .SE (n_316), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[8] [7]),
       .SE (n_316), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[9][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[9] [0]),
       .SE (n_315), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[9] [1]),
       .SE (n_315), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[9] [2]),
       .SE (n_315), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[9][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[9] [3]),
       .SE (n_315), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[9][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[9] [4]),
       .SE (n_315), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[9] [6]),
       .SE (n_315), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[9][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[9] [7]),
       .SE (n_315), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[11][4] (.CK (wclk), .D (\mem[11] [4]), .SI
       (wdata[4]), .SE (n_322), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[8][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[8] [6]),
       .SE (n_316), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[11][6] (.CK (wclk), .D (\mem[11] [6]), .SI
       (wdata[6]), .SE (n_322), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[11][5] (.CK (wclk), .D (\mem[11] [5]), .SI
       (wdata[5]), .SE (n_322), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[0] [2]),
       .SE (n_320), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[13][1] (.CK (wclk), .D (\mem[13] [1]), .SI
       (wdata[1]), .SE (n_319), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[13][2] (.CK (wclk), .D (\mem[13] [2]), .SI
       (wdata[2]), .SE (n_319), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][4] (.CK (wclk), .D (\mem[13] [4]), .SI
       (wdata[4]), .SE (n_319), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[13][5] (.CK (wclk), .D (\mem[13] [5]), .SI
       (wdata[5]), .SE (n_319), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[13][6] (.CK (wclk), .D (\mem[13] [6]), .SI
       (wdata[6]), .SE (n_319), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[2][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[2] [6]),
       .SE (n_318), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[0] [4]),
       .SE (n_320), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[4][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[4] [5]),
       .SE (n_321), .Q (\mem[4] [5]));
  XNOR2X1 g12520__5477(.A (n_285), .B (n_312), .Y (n_314));
  XNOR2X1 g12521__2398(.A (n_312), .B (n_311), .Y (n_313));
  NOR2XL g12601__5107(.A (n_379), .B (n_391), .Y (n_310));
  AOI221X1 g12603__6260(.A0 (\mem[15] [4]), .A1 (n_372), .B0
       (\mem[6] [4]), .B1 (n_192), .C0 (n_238), .Y (n_309));
  NOR2XL g12604__4319(.A (n_375), .B (n_392), .Y (n_308));
  NOR2XL g12607__8428(.A (n_390), .B (n_377), .Y (n_307));
  NOR2XL g12608__5526(.A (n_389), .B (n_374), .Y (n_306));
  NOR2X1 g12609__6783(.A (n_383), .B (n_380), .Y (n_305));
  NOR2XL g12610__3680(.A (n_388), .B (n_387), .Y (n_304));
  NOR2XL g12611__1617(.A (n_376), .B (n_378), .Y (n_303));
  NOR2XL g12612__2802(.A (n_366), .B (n_381), .Y (n_302));
  NOR2XL g12613__1705(.A (n_384), .B (n_382), .Y (n_301));
  NOR2XL g12614__5122(.A (n_386), .B (n_385), .Y (n_300));
  DFFRHQX1 \rbin_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_279), .Q
       (rbin[4]));
  SDFFQX1 \mem_reg[1][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[1] [5]),
       .SE (n_299), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[5][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[5] [6]),
       .SE (n_298), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[1][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[1] [2]),
       .SE (n_299), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[5][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[5] [2]),
       .SE (n_298), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[1][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[1] [3]),
       .SE (n_299), .Q (\mem[1] [3]));
  DFFRHQX1 \wbin_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_280), .Q
       (wbin[2]));
  SDFFQX1 \mem_reg[3][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[3] [7]),
       .SE (n_296), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[1][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[1] [4]),
       .SE (n_299), .Q (\mem[1] [4]));
  MXI2X1 g12579__8246(.A (n_290), .B (n_281), .S0 (n_297), .Y (n_324));
  SDFFQX1 \mem_reg[1][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[1] [7]),
       .SE (n_299), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[1][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[1] [6]),
       .SE (n_299), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[3][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[3] [0]),
       .SE (n_296), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[3][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[3] [1]),
       .SE (n_296), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[3] [3]),
       .SE (n_296), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[3][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[3] [5]),
       .SE (n_296), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[5][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[5] [0]),
       .SE (n_298), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[5] [1]),
       .SE (n_298), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[5][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[5] [3]),
       .SE (n_298), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[5][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[5] [4]),
       .SE (n_298), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[5] [5]),
       .SE (n_298), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[5] [7]),
       .SE (n_298), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[3][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[3] [4]),
       .SE (n_296), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[3] [6]),
       .SE (n_296), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[3] [2]),
       .SE (n_296), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[1][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[1] [1]),
       .SE (n_299), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[1][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[1] [0]),
       .SE (n_299), .Q (\mem[1] [0]));
  INVX1 g12600(.A (n_340), .Y (n_295));
  SDFFQX1 \mem_reg[15][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[15]
       [0]), .SE (n_294), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[15]
       [1]), .SE (n_294), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[15]
       [2]), .SE (n_294), .Q (\mem[15] [2]));
  SDFFQX1 \mem_reg[15][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[15]
       [3]), .SE (n_294), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[15]
       [6]), .SE (n_294), .Q (\mem[15] [6]));
  SDFFQX1 \mem_reg[15][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[15]
       [4]), .SE (n_294), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[15]
       [5]), .SE (n_294), .Q (\mem[15] [5]));
  DFFRHQX1 \rbin_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_291), .Q
       (rbin[2]));
  NOR2X1 g12624__7098(.A (n_237), .B (n_239), .Y (n_293));
  NOR2XL g12605__6131(.A (n_291), .B (n_290), .Y (n_292));
  NAND2XL g12606__1881(.A (n_291), .B (n_290), .Y (n_289));
  NOR2XL g12628__5115(.A (n_179), .B (n_233), .Y (n_288));
  NOR2X1 g12623__7482(.A (n_241), .B (n_243), .Y (n_287));
  NOR2X1 g12625__6161(.A (n_235), .B (n_240), .Y (n_284));
  NOR2XL g12626__9315(.A (n_440), .B (n_245), .Y (n_283));
  NOR2X1 g12627__9945(.A (n_234), .B (n_242), .Y (n_282));
  SDFFQX1 \mem_reg[15][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[15]
       [7]), .SE (n_294), .Q (\mem[15] [7]));
  DFFRHQX4 \rbin_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_281), .Q
       (rbin[3]));
  INVX1 g12642(.A (n_312), .Y (n_280));
  INVXL g12641(.A (n_297), .Y (n_279));
  SDFFQX1 \mem_reg[7][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[7] [3]),
       .SE (n_263), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[7] [6]),
       .SE (n_263), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[7][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[7] [2]),
       .SE (n_263), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[7] [1]),
       .SE (n_263), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[7] [5]),
       .SE (n_263), .Q (\mem[7] [5]));
  XNOR2X1 g12619__8428(.A (n_145), .B (n_198), .Y (n_340));
  DFFRHQX1 \rbin_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_262), .Q
       (rbin[1]));
  NOR3X1 g12659__7098(.A (n_160), .B (n_167), .C (n_174), .Y (n_251));
  NOR3X1 g12657__5115(.A (n_166), .B (n_165), .C (n_171), .Y (n_248));
  NOR3X1 g12658__7482(.A (n_163), .B (n_161), .C (n_175), .Y (n_247));
  SDFFQX1 \mem_reg[7][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[7] [7]),
       .SE (n_263), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[7][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[7] [0]),
       .SE (n_263), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[7] [4]),
       .SE (n_263), .Q (\mem[7] [4]));
  NOR2X1 g12687__4733(.A (n_172), .B (n_246), .Y (n_326));
  NOR2X1 g12683__6161(.A (n_227), .B (n_246), .Y (n_327));
  NOR2X1 g12678__9315(.A (n_226), .B (n_246), .Y (n_328));
  OAI2BB1X1 g12712__9945(.A0N (\mem[15] [1]), .A1N (n_372), .B0
       (n_176), .Y (n_245));
  DFFRHQX1 \wbin_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_214), .Q
       (wbin[0]));
  OAI2BB1X1 g12707__2883(.A0N (\mem[15] [3]), .A1N (n_372), .B0
       (n_191), .Y (n_243));
  OAI2BB1X1 g12708__2346(.A0N (\mem[15] [6]), .A1N (n_372), .B0
       (n_193), .Y (n_242));
  NAND2X1 g12709__1666(.A (n_195), .B (n_190), .Y (n_241));
  OAI2BB1X1 g12710__7410(.A0N (\mem[15] [2]), .A1N (n_372), .B0
       (n_185), .Y (n_240));
  OAI2BB1X1 g12711__6417(.A0N (\mem[15] [5]), .A1N (n_372), .B0
       (n_183), .Y (n_239));
  NOR2XL g12622__5477(.A (n_270), .B (n_177), .Y (n_238));
  NAND2X1 g12713__2398(.A (n_186), .B (n_184), .Y (n_237));
  NAND2X1 g12715__6260(.A (n_187), .B (n_188), .Y (n_235));
  NAND2X1 g12716__4319(.A (n_181), .B (n_178), .Y (n_234));
  NAND2X1 g12717__8428(.A (n_105), .B (n_180), .Y (n_233));
  NAND2X1 g12637__5526(.A (n_263), .B (n_173), .Y (n_311));
  DFFRHQX1 \wbin_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_285), .Q
       (wbin[1]));
  OAI21XL g12656__6783(.A0 (n_412), .A1 (n_415), .B0 (n_230), .Y
       (n_232));
  OAI21XL g12646__3680(.A0 (n_402), .A1 (n_394), .B0 (n_230), .Y
       (n_231));
  XNOR2X1 g12660__1617(.A (n_2), .B (n_169), .Y (n_264));
  INVX1 g12644(.A (n_290), .Y (n_281));
  AOI211XL g12662__2802(.A0 (wbin[2]), .A1 (n_182), .B0 (n_229), .C0
       (n_155), .Y (n_312));
  XNOR2X1 g12661__1705(.A (rbin[4]), .B (n_150), .Y (n_297));
  XNOR2X1 g12663__5122(.A (n_6), .B (n_148), .Y (n_291));
  NAND2X1 g12679__8246(.A (n_229), .B (n_228), .Y (n_321));
  NAND2X1 g12680__7098(.A (n_56), .B (n_228), .Y (n_317));
  NOR2X1 g12681__6131(.A (n_227), .B (n_370), .Y (n_319));
  NOR2X1 g12682__1881(.A (n_226), .B (n_370), .Y (n_322));
  NAND2X1 g12684__5115(.A (n_212), .B (n_228), .Y (n_318));
  NAND2X1 g12686__7482(.A (n_224), .B (n_228), .Y (n_320));
  OR2X1 g12688__4733(.A (n_11), .B (n_370), .Y (n_315));
  NAND2X1 g12689__6161(.A (n_224), .B (n_213), .Y (n_316));
  INVX1 g12721(.A (n_213), .Y (n_246));
  DFFRHQX4 \rbin_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_146), .Q
       (rbin[0]));
  CLKXOR2X1 g12664__2398(.A (rbin[3]), .B (n_106), .Y (n_290));
  NAND2X2 g12690__5107(.A (n_229), .B (n_211), .Y (n_298));
  NAND2X2 g12691__6260(.A (n_212), .B (n_211), .Y (n_296));
  INVX1 g12692(.A (n_198), .Y (n_262));
  NAND2X2 g12685__1881(.A (n_224), .B (n_211), .Y (n_299));
  NAND2XL g12738__7482(.A (\mem[14] [1]), .B (n_189), .Y (n_196));
  NAND2XL g12722__4733(.A (\mem[7] [3]), .B (n_371), .Y (n_195));
  NAND2X1 g12724__6161(.A (\mem[6] [6]), .B (n_192), .Y (n_193));
  NAND2X1 g12725__9315(.A (\mem[6] [3]), .B (n_192), .Y (n_191));
  NAND2XL g12726__9945(.A (\mem[14] [3]), .B (n_189), .Y (n_190));
  NAND2XL g12730__2883(.A (\mem[14] [2]), .B (n_189), .Y (n_188));
  NAND2XL g12731__2346(.A (\mem[7] [2]), .B (n_371), .Y (n_187));
  NAND2XL g12732__1666(.A (\mem[7] [5]), .B (n_371), .Y (n_186));
  NAND2X1 g12733__7410(.A (\mem[6] [2]), .B (n_192), .Y (n_185));
  NAND2XL g12734__6417(.A (\mem[14] [5]), .B (n_189), .Y (n_184));
  NAND2X1 g12735__5477(.A (\mem[6] [5]), .B (n_192), .Y (n_183));
  MXI2X1 g12719__2398(.A (n_5), .B (rbin[1]), .S0 (n_149), .Y (n_198));
  XNOR2X1 g12718__5107(.A (wbin[1]), .B (n_182), .Y (n_285));
  NAND2XL g12741__6260(.A (\mem[7] [6]), .B (n_371), .Y (n_181));
  NAND2XL g12742__4319(.A (\mem[14] [4]), .B (n_189), .Y (n_180));
  AND2XL g12744__8428(.A (\mem[7] [4]), .B (n_371), .Y (n_179));
  NAND2XL g12745__5526(.A (\mem[14] [6]), .B (n_189), .Y (n_178));
  AOI22XL g12706__6783(.A0 (n_10), .A1 (n_27), .B0 (\mem[1] [4]), .B1
       (n_158), .Y (n_177));
  NAND2X1 g12740__3680(.A (\mem[6] [1]), .B (n_192), .Y (n_176));
  AOI21X1 g12671__1617(.A0 (n_45), .A1 (n_51), .B0 (n_270), .Y (n_175));
  AOI21X1 g12667__2802(.A0 (n_32), .A1 (n_97), .B0 (n_270), .Y (n_174));
  OAI21X1 g12705__1705(.A0 (n_172), .A1 (n_182), .B0 (wbin[3]), .Y
       (n_173));
  AOI21X1 g12666__5122(.A0 (n_102), .A1 (n_83), .B0 (n_270), .Y
       (n_171));
  OAI2BB1X1 g12759__8246(.A0N (n_58), .A1N (n_107), .B0 (n_170), .Y
       (n_214));
  NOR2X1 g12760__7098(.A (n_57), .B (n_170), .Y (n_213));
  NOR2X2 g12761__1881(.A (wbin[3]), .B (n_170), .Y (n_228));
  INVX1 g12763(.A (n_169), .Y (n_294));
  NOR2BX1 g12727__7482(.AN (\mem[0] [6]), .B (n_164), .Y (n_167));
  NOR2BX1 g12728__4733(.AN (\mem[9] [5]), .B (n_162), .Y (n_166));
  NOR2BX1 g12729__6161(.AN (\mem[0] [5]), .B (n_164), .Y (n_165));
  NOR2BX1 g12736__9315(.AN (\mem[9] [1]), .B (n_162), .Y (n_163));
  NOR2BX1 g12737__9945(.AN (\mem[0] [1]), .B (n_164), .Y (n_161));
  NOR2BX1 g12743__2883(.AN (\mem[9] [6]), .B (n_162), .Y (n_160));
  OAI2BB1X1 g12747__1666(.A0N (\mem[4] [5]), .A1N (n_153), .B0 (n_67),
       .Y (n_157));
  NOR2X1 g12749__6417(.A (n_226), .B (n_182), .Y (n_155));
  OAI2BB1X1 g12751__5477(.A0N (\mem[4] [2]), .A1N (n_153), .B0 (n_38),
       .Y (n_154));
  NOR2XL g12754__6260(.A (n_20), .B (n_149), .Y (n_150));
  NOR2BX1 g12756__4319(.AN (rreq), .B (n_92), .Y (n_148));
  INVX1 g12762(.A (n_145), .Y (n_146));
  NAND2X1 g12765__6783(.A (n_82), .B (n_39), .Y (n_143));
  OAI2BB1X1 g12766__3680(.A0N (\mem[0] [2]), .A1N (n_153), .B0 (n_76),
       .Y (n_142));
  NAND2X1 g12770__5122(.A (n_41), .B (n_40), .Y (n_138));
  NAND2X1 g12772__7098(.A (n_84), .B (n_44), .Y (n_136));
  NOR2X1 g12758__6131(.A (wbin[3]), .B (n_182), .Y (n_211));
  OAI2BB1X1 g12788__1881(.A0N (\mem[0] [0]), .A1N (n_153), .B0 (n_81),
       .Y (n_135));
  OAI2BB1X1 g12775__5115(.A0N (\mem[3] [7]), .A1N (n_158), .B0 (n_31),
       .Y (n_134));
  OAI2BB1X1 g12778__6161(.A0N (\mem[4] [7]), .A1N (n_153), .B0 (n_54),
       .Y (n_131));
  OAI2BB1X1 g12779__9315(.A0N (\mem[4] [1]), .A1N (n_153), .B0 (n_72),
       .Y (n_130));
  NAND2X1 g12780__9945(.A (n_65), .B (n_71), .Y (n_129));
  OAI2BB1X1 g12781__2883(.A0N (\mem[10] [7]), .A1N (n_104), .B0
       (n_100), .Y (n_128));
  NAND2X1 g12782__2346(.A (n_26), .B (n_98), .Y (n_127));
  OAI2BB1X1 g12783__1666(.A0N (\mem[4] [4]), .A1N (n_153), .B0 (n_48),
       .Y (n_126));
  OAI2BB1X1 g12784__7410(.A0N (\mem[2] [6]), .A1N (n_153), .B0 (n_86),
       .Y (n_125));
  OAI2BB1X1 g12785__6417(.A0N (\mem[2] [4]), .A1N (n_153), .B0 (n_64),
       .Y (n_124));
  OAI2BB1X1 g12774__5107(.A0N (\mem[2] [5]), .A1N (n_153), .B0 (n_79),
       .Y (n_121));
  OAI2BB1X1 g12793__6783(.A0N (\mem[4] [6]), .A1N (n_153), .B0 (n_68),
       .Y (n_115));
  OAI2BB1X1 g12796__2802(.A0N (\mem[0] [3]), .A1N (n_153), .B0 (n_62),
       .Y (n_112));
  OAI2BB1X1 g12797__1705(.A0N (\mem[2] [1]), .A1N (n_153), .B0 (n_24),
       .Y (n_111));
  OAI2BB1X1 g12798__5122(.A0N (\mem[4] [3]), .A1N (n_153), .B0 (n_28),
       .Y (n_110));
  NAND2X1 g12799__8246(.A (n_66), .B (n_69), .Y (n_109));
  NOR2X1 g12803__6131(.A (n_25), .B (n_13), .Y (n_169));
  OR2X1 g12802__1881(.A (n_107), .B (n_59), .Y (n_263));
  NAND3X1 g12755__5115(.A (n_19), .B (rreq), .C (n_91), .Y (n_106));
  NAND3BXL g12750__7482(.AN (n_270), .B (\mem[8] [4]), .C (n_104), .Y
       (n_105));
  MXI2XL g12801__4733(.A (n_426), .B (n_427), .S0 (n_8), .Y (n_145));
  NAND2X2 g12886__6161(.A (wreq), .B (n_14), .Y (n_170));
  NOR2X2 g12889__9945(.A (n_273), .B (n_16), .Y (n_192));
  NOR2X2 g12891__2346(.A (n_273), .B (n_17), .Y (n_189));
  NAND2XL g12824__1666(.A (\mem[1] [5]), .B (n_158), .Y (n_102));
  NAND2X1 g12806__6417(.A (\mem[2] [7]), .B (n_153), .Y (n_100));
  NAND2XL g12808__2398(.A (\mem[12] [7]), .B (n_104), .Y (n_98));
  NAND2XL g12809__5107(.A (\mem[8] [6]), .B (n_104), .Y (n_97));
  NAND2X1 g12814__6783(.A (rbin[1]), .B (n_91), .Y (n_92));
  NAND2XL g12819__5122(.A (\mem[11] [6]), .B (n_441), .Y (n_86));
  NAND2XL g12821__7098(.A (\mem[5] [4]), .B (n_158), .Y (n_84));
  NAND2XL g12822__6131(.A (\mem[8] [5]), .B (n_104), .Y (n_83));
  NAND2XL g12823__1881(.A (\mem[15] [7]), .B (n_441), .Y (n_82));
  NAND2XL g12804__5115(.A (\mem[9] [0]), .B (n_441), .Y (n_81));
  NAND2XL g12826__4733(.A (\mem[11] [5]), .B (n_441), .Y (n_79));
  NAND2XL g12829__9945(.A (\mem[9] [2]), .B (n_441), .Y (n_76));
  NAND2XL g12833__7410(.A (\mem[13] [1]), .B (n_441), .Y (n_72));
  NAND2XL g12834__6417(.A (\mem[12] [0]), .B (n_104), .Y (n_71));
  NAND2XL g12837__2398(.A (\mem[12] [3]), .B (n_104), .Y (n_69));
  NAND2XL g12838__5107(.A (\mem[13] [6]), .B (n_441), .Y (n_68));
  NAND2XL g12839__6260(.A (\mem[13] [5]), .B (n_441), .Y (n_67));
  NAND2XL g12840__4319(.A (\mem[5] [3]), .B (n_158), .Y (n_66));
  NAND2XL g12841__8428(.A (\mem[5] [0]), .B (n_158), .Y (n_65));
  NAND2XL g12842__5526(.A (\mem[11] [4]), .B (n_441), .Y (n_64));
  NAND2XL g12844__3680(.A (\mem[9] [3]), .B (n_441), .Y (n_62));
  NAND3X1 g12849__1705(.A (n_58), .B (n_57), .C (n_56), .Y (n_59));
  NAND2XL g12851__8246(.A (\mem[13] [7]), .B (n_441), .Y (n_54));
  NAND2XL g12854__1881(.A (\mem[8] [1]), .B (n_104), .Y (n_51));
  NAND2XL g12857__4733(.A (\mem[13] [4]), .B (n_441), .Y (n_48));
  NAND2XL g12860__9945(.A (\mem[1] [1]), .B (n_158), .Y (n_45));
  NAND2XL g12861__2883(.A (\mem[12] [4]), .B (n_104), .Y (n_44));
  NAND2XL g12864__7410(.A (\mem[11] [0]), .B (n_441), .Y (n_41));
  NAND2X1 g12865__6417(.A (\mem[2] [0]), .B (n_153), .Y (n_40));
  NAND2X1 g12866__5477(.A (\mem[6] [7]), .B (n_153), .Y (n_39));
  NAND2XL g12845__2398(.A (\mem[13] [2]), .B (n_441), .Y (n_38));
  NAND2XL g12873__6783(.A (\mem[1] [6]), .B (n_158), .Y (n_32));
  NAND2XL g12874__3680(.A (\mem[11] [7]), .B (n_441), .Y (n_31));
  NAND2XL g12878__1705(.A (\mem[13] [3]), .B (n_441), .Y (n_28));
  OR2XL g12879__5122(.A (rbin[3]), .B (n_373), .Y (n_27));
  NAND2XL g12880__8246(.A (\mem[5] [7]), .B (n_158), .Y (n_26));
  NAND2X1 g12881__7098(.A (wbin[3]), .B (n_21), .Y (n_25));
  NAND2XL g12877__6131(.A (\mem[11] [1]), .B (n_441), .Y (n_24));
  NAND2X1 g12884__5115(.A (rreq), .B (n_91), .Y (n_149));
  NAND2X1 g12887__7482(.A (n_22), .B (n_441), .Y (n_162));
  NAND2XL g12885__4733(.A (n_22), .B (n_153), .Y (n_164));
  NAND2X4 g12892__6161(.A (wreq), .B (n_21), .Y (n_182));
  NAND2X1 g12882__9315(.A (rbin[3]), .B (n_19), .Y (n_20));
  INVX1 g12895(.A (n_226), .Y (n_212));
  INVX1 g12896(.A (n_229), .Y (n_227));
  INVX1 g12908(.A (n_259), .Y (n_230));
  INVX2 g12912(.A (n_104), .Y (n_17));
  INVX2 g12910(.A (n_153), .Y (n_16));
  NOR2X2 g12914__9945(.A (wfull), .B (n_58), .Y (n_14));
  NAND2X1 g12835__2883(.A (wreq), .B (n_56), .Y (n_13));
  INVXL g12893(.A (n_224), .Y (n_11));
  OAI2BB1X1 g12883__1666(.A0N (\mem[9] [4]), .A1N (rbin[0]), .B0
       (rbin[3]), .Y (n_10));
  NOR2X2 g12899__7410(.A (wfull), .B (n_3), .Y (n_21));
  INVX1 g12894(.A (n_56), .Y (n_172));
  INVX1 g12909(.A (n_270), .Y (n_22));
  NOR2X2 g12915__6417(.A (rempty), .B (n_428), .Y (n_91));
  INVX1 g12897(.A (n_19), .Y (n_273));
  NAND2X1 g12901__5477(.A (n_1), .B (rreq), .Y (n_8));
  NAND2X1 g12904__2398(.A (wbin[1]), .B (n_7), .Y (n_226));
  NOR2X1 g12905__5107(.A (wbin[1]), .B (n_7), .Y (n_229));
  NAND2X1 g12916__6260(.A (rbin[1]), .B (n_6), .Y (n_259));
  NAND2X1 g12917__4319(.A (rbin[2]), .B (n_5), .Y (n_275));
  CLKAND2X4 g12919__5526(.A (n_432), .B (n_438), .Y (n_153));
  CLKAND2X4 g12921__6783(.A (rbin[3]), .B (n_432), .Y (n_104));
  NOR2X4 g12920__3680(.A (rbin[3]), .B (n_433), .Y (n_158));
  NAND2BX1 g12900__1617(.AN (wfull), .B (wreq), .Y (n_107));
  CLKAND2X2 g12906__2802(.A (rbin[2]), .B (rbin[1]), .Y (n_19));
  CLKAND2X2 g12903__1705(.A (wbin[2]), .B (wbin[1]), .Y (n_56));
  INVX1 g12925(.A (n_3), .Y (n_58));
  NOR2X1 g12902__5122(.A (wbin[2]), .B (wbin[1]), .Y (n_224));
  OR2X1 g12918__8246(.A (rbin[2]), .B (rbin[1]), .Y (n_270));
  INVX1 g12931(.A (rbin[2]), .Y (n_6));
  INVX1 g12927(.A (wbin[2]), .Y (n_7));
  INVX1 g12928(.A (rbin[1]), .Y (n_5));
  INVX1 g12926(.A (wbin[0]), .Y (n_3));
  AOI2BB1XL g2(.A0N (n_110), .A1N (n_109), .B0 (n_275), .Y (n_366));
  DFFRX1 \rq2_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (rq1_wptr[3]),
       .Q (rq2_wptr[3]), .QN (n_343));
  DFFRX1 \rq2_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (rq1_wptr[2]),
       .Q (rq2_wptr[2]), .QN (n_342));
  DFFRX1 \wbin_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_264), .Q
       (wbin[4]), .QN (n_2));
  DFFRXL rempty_reg(.RN (rrst_n), .CK (rclk), .D (n_358), .Q (rempty),
       .QN (n_1));
  DFFRX1 \wbin_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_311), .Q
       (wbin[3]), .QN (n_57));
  XOR2XL g13107(.A (n_264), .B (n_311), .Y (n_367));
  XNOR2X1 g13108(.A (n_262), .B (n_291), .Y (n_368));
  XOR2XL g13109(.A (n_214), .B (n_285), .Y (n_369));
  NAND2BX1 g13110(.AN (n_182), .B (wbin[3]), .Y (n_370));
  NOR2BX1 g13111(.AN (n_158), .B (n_273), .Y (n_371));
  NOR2BX1 g13112(.AN (n_441), .B (n_273), .Y (n_372));
  NOR2BXL g13113(.AN (\mem[0] [4]), .B (rbin[0]), .Y (n_373));
  AOI2BB1XL g13114(.A0N (n_399), .A1N (n_401), .B0 (n_273), .Y (n_374));
  AOI2BB1XL g13115(.A0N (n_157), .A1N (n_403), .B0 (n_275), .Y (n_375));
  AOI2BB1XL g13116(.A0N (n_154), .A1N (n_400), .B0 (n_275), .Y (n_376));
  AOI2BB1XL g13117(.A0N (n_143), .A1N (n_411), .B0 (n_273), .Y (n_377));
  AOI2BB1XL g13118(.A0N (n_142), .A1N (n_398), .B0 (n_270), .Y (n_378));
  AOI2BB1XL g13119(.A0N (n_135), .A1N (n_397), .B0 (n_270), .Y (n_379));
  AOI2BB1XL g13120(.A0N (n_396), .A1N (n_413), .B0 (n_270), .Y (n_380));
  AOI2BB1XL g13121(.A0N (n_112), .A1N (n_418), .B0 (n_270), .Y (n_381));
  AOI2BB1XL g13122(.A0N (n_125), .A1N (n_395), .B0 (n_259), .Y (n_382));
  AOI2BB1XL g13123(.A0N (n_134), .A1N (n_128), .B0 (n_259), .Y (n_383));
  AOI2BB1XL g13124(.A0N (n_115), .A1N (n_393), .B0 (n_275), .Y (n_384));
  AOI2BB1XL g13125(.A0N (n_111), .A1N (n_405), .B0 (n_259), .Y (n_385));
  AOI2BB1XL g13126(.A0N (n_130), .A1N (n_406), .B0 (n_275), .Y (n_386));
  AOI2BB1XL g13127(.A0N (n_124), .A1N (n_414), .B0 (n_259), .Y (n_387));
  AOI2BB1XL g13128(.A0N (n_126), .A1N (n_136), .B0 (n_275), .Y (n_388));
  AOI2BB1XL g13129(.A0N (n_129), .A1N (n_416), .B0 (n_275), .Y (n_389));
  AOI2BB1XL g13130(.A0N (n_131), .A1N (n_127), .B0 (n_275), .Y (n_390));
  AOI2BB1XL g13131(.A0N (n_138), .A1N (n_409), .B0 (n_259), .Y (n_391));
  AOI2BB1XL g13132(.A0N (n_121), .A1N (n_410), .B0 (n_259), .Y (n_392));
  AO22XL g13133(.A0 (\mem[5] [6]), .A1 (n_158), .B0 (\mem[12] [6]), .B1
       (n_104), .Y (n_393));
  AO22XL g13134(.A0 (\mem[3] [2]), .A1 (n_158), .B0 (\mem[10] [2]), .B1
       (n_104), .Y (n_394));
  AO22XL g13135(.A0 (\mem[3] [6]), .A1 (n_158), .B0 (\mem[10] [6]), .B1
       (n_104), .Y (n_395));
  AO22XL g13136(.A0 (\mem[9] [7]), .A1 (n_441), .B0 (\mem[0] [7]), .B1
       (n_153), .Y (n_396));
  AO22XL g13137(.A0 (\mem[1] [0]), .A1 (n_158), .B0 (\mem[8] [0]), .B1
       (n_104), .Y (n_397));
  AO22XL g13138(.A0 (\mem[1] [2]), .A1 (n_158), .B0 (\mem[8] [2]), .B1
       (n_104), .Y (n_398));
  AO22XL g13139(.A0 (\mem[15] [0]), .A1 (n_441), .B0 (\mem[6] [0]), .B1
       (n_153), .Y (n_399));
  AO22XL g13140(.A0 (\mem[5] [2]), .A1 (n_158), .B0 (\mem[12] [2]), .B1
       (n_104), .Y (n_400));
  AO22XL g13141(.A0 (\mem[7] [0]), .A1 (n_158), .B0 (\mem[14] [0]), .B1
       (n_104), .Y (n_401));
  AO22XL g13142(.A0 (\mem[11] [2]), .A1 (n_441), .B0 (\mem[2] [2]), .B1
       (n_153), .Y (n_402));
  AO22XL g13143(.A0 (\mem[5] [5]), .A1 (n_158), .B0 (\mem[12] [5]), .B1
       (n_104), .Y (n_403));
  AO22XL g13145(.A0 (\mem[3] [1]), .A1 (n_158), .B0 (\mem[10] [1]), .B1
       (n_104), .Y (n_405));
  AO22XL g13146(.A0 (\mem[5] [1]), .A1 (n_158), .B0 (\mem[12] [1]), .B1
       (n_104), .Y (n_406));
  AO22XL g13149(.A0 (\mem[3] [0]), .A1 (n_158), .B0 (\mem[10] [0]), .B1
       (n_104), .Y (n_409));
  AO22XL g13150(.A0 (\mem[3] [5]), .A1 (n_158), .B0 (\mem[10] [5]), .B1
       (n_104), .Y (n_410));
  AO22XL g13151(.A0 (\mem[7] [7]), .A1 (n_158), .B0 (\mem[14] [7]), .B1
       (n_104), .Y (n_411));
  AO22XL g13152(.A0 (\mem[11] [3]), .A1 (n_441), .B0 (\mem[2] [3]), .B1
       (n_153), .Y (n_412));
  AO22XL g13153(.A0 (\mem[1] [7]), .A1 (n_158), .B0 (\mem[8] [7]), .B1
       (n_104), .Y (n_413));
  AO22XL g13154(.A0 (\mem[3] [4]), .A1 (n_158), .B0 (\mem[10] [4]), .B1
       (n_104), .Y (n_414));
  AO22XL g13155(.A0 (\mem[3] [3]), .A1 (n_158), .B0 (\mem[10] [3]), .B1
       (n_104), .Y (n_415));
  AO22XL g13156(.A0 (\mem[13] [0]), .A1 (n_441), .B0 (\mem[4] [0]), .B1
       (n_153), .Y (n_416));
  AO22XL g13158(.A0 (\mem[1] [3]), .A1 (n_158), .B0 (\mem[8] [3]), .B1
       (n_104), .Y (n_418));
  INVX1 fopt5(.A (n_427), .Y (n_426));
  INVX1 fopt6(.A (n_428), .Y (n_427));
  INVX1 fopt7(.A (rbin[0]), .Y (n_428));
  INVX3 fopt9(.A (rbin[0]), .Y (n_432));
  INVX2 fopt10(.A (rbin[0]), .Y (n_433));
  INVX2 fopt2(.A (rbin[3]), .Y (n_438));
  OAI2BB1X1 g13159(.A0N (\mem[7] [1]), .A1N (n_371), .B0 (n_196), .Y
       (n_440));
  CLKAND2X3 g13160(.A (rbin[3]), .B (rbin[0]), .Y (n_441));
endmodule

